### ISSUE TITLE
Suggestion: safer and lighter alternative

### ISSUE THREAD

**Issue by rabelloo** [takagg/genshin-impact-helper#1]
Hey, hope you don't take it personally, but I found the code to be super sketchy, can't tell for sure whether the auth cookie is safe.

So I developed an alternative that is really straight forward, any coder with basic scripting knowledge will be able to tell the cookie is safe in there.

Feel free to try it out, and if you think it's good please let the community know.

https://github.com/rabelloo/genshin-daily

It essentially just opens the website on a browser like any person would and actually clicks the icon.

Also the method for extracting the cookie should be a little bit safer too, involves no 3rd-party script.

**Comment by HSAK5G** [comment]
Great jon will use this instead
