### ISSUE TITLE
Linux computer

### ISSUE THREAD

**Issue by HSAK5G** [takagg/genshin-impact-helper#2]
I basically have a linux computer that is always on so is it possible to run this script on the laptop instead of GitHub. If so then please send instructions.

**Comment by napkatti** [comment]
Just schedule `python3 ./genshin-os.py` with `cron`.

The only difference will be where your cookie is stored. Since it's your personal computer might as well just hardcode the cookie into the script instead of worrying about setting up environment variables properly.

**Comment by HSAK5G** [comment]
ok thx
