### ISSUE TITLE
English translation and removal of Chinese social media

### ISSUE THREAD

**Issue by napkatti** [takagg/genshin-impact-helper#3]
As someone else has already voiced their concerns about the safety of trusting this project in [#1 ], I have decided to fully translate the project from Chinese to English and remove the references to Chinese social media that people are getting suspicious over.

Unlike the project in [#1], I am not rebuilding the tool from the ground up in a different framework, but instead trimming down the existing code.

See my fork on https://github.com/napkatti/genshin-impact-helper

Since my fork is based on yours, it is suitable for a direct pull request if you are interested.

Please respond via this issue here or speak with me over Discord in the autocheckin-chat channel or by DM.

**Comment by takagg** [comment]
Reviewed and merged, thanks for helping out.
