### ISSUE TITLE
Error: Process completed with exit code 255

### ISSUE THREAD

**Issue by HawkMoth250** [takagg/genshin-impact-helper#7]
Thre is an error in build. Stage run sign. Please, HELP! I try to restart, change and remove secret – didn't work
![issue](https://user-images.githubusercontent.com/71706000/116492986-5dff9300-a8a6-11eb-9428-c4b8aa92b8d0.png)

**Comment by LagSeeN** [comment]
your cookie_os must have cookie_token="" ltoken="" ltuid="" check in your setting
