### ISSUE TITLE
cron job time

### ISSUE THREAD

**Issue by jasonwkl** [takagg/genshin-impact-helper#9]
Thanks for the great tool.

Noob here, I wonder if it is possible to use random generator for the minutes/hour so that it does not seem like we are running a bot from Mihoyo's perspective. Kinda worried that my acc will get banned. 

Then again, the ip address of all our automation is probably from the same source. is that right?

**Comment by takagg** [comment]
You can edit the running time by editing the cron time in .github/workflows/main-os.yml 

Big web services such as Github Actions use horizontal servers running in parallel to avoid service disruption. So I think the possibilities of actions sending from the same server is quite small.
